### ISSUE TITLE
Do installation handling now

### ISSUE THREAD

**Issue by LittleRichard** [LittleRichard/sormtger#10]
Before we install anything else, get the core install path working.  At completion, there should be two files in the repository (see below).  At completion, this should be able to take a bare bones raspian image and turn it into a fully working server.

IT MUST BE KEPT UPDATED as we install more stuff, so make an easy-to-copy test of this for any significant package imports/additions.

bootstrap.sh
* start with a clean bare bones raspian
* configure internet access
* move this script to /home/name_of_user
* run it to:
  * install git
  * install python2.7
  * clone this repository
  * cd into install.sh
  * execute install.sh

install.sh
* assumes this repository exists
* this should be repeatable to trigger an update of an existing installation
* apt-get all relevant packages
* run apt-get of all necessary packages
* pip install -r requirements.txt
* stub out set_up_database.sh
  * (eventually, prepare/migrate database with python script)
* stub out update_databases.sh
  * (eventually, download database information with python script. should be repeatable to update an existing database)
* run a basic test to make sure everything is wired up
* set everything to run on startup
* start the server

The server will be responsible for providing a UI to configure the user's modular setup and do further testing.

**Comment by LittleRichard** [comment]
@Panzer23 I should be able to do it without borrowing the RPi and wiping it over and over by setting up a VM.  Can you do me a favor when you get a chance and post the output of running the following command in a kernel?  
`uname -a`

My work laptop outputs the following, the Raspbian should be similar except talk about Debians and Jessie
`Linux dev-t-tahr 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Also, I know you did the net install for #6 , is there a reason you'd prefer to continue doing that as the 'clean install' methodology? Or, is it okay to make a base image for our project that has just the raw kernel plus the bootstrap shell script that I'll develop as part of this ticket (which should never change).  That way anytime we need to make a new SD card we can just flash that image, boot the RPi, and execute bootstrap.sh

Code upgrades of an existing installation should be possible by just running the 'install.sh' (or if i have to split out some of it, i'll make an 'update.sh')

**Comment by Panzer23** [comment]
@LittleRichard  Question 1: answered when I get home from work.
Question 2:  No reason,  I tried both ways when I set up the RPi and neither worked at first.  This way was just the first way that it worked.  clean install way kept boot looping or stalling when trying to install a username service or some shit.  Would like to note that RPi just came out with a new update for its jessie image yesterday.

**Comment by LittleRichard** [comment]
Hey @Panzer23 , can you try

`
wget https://raw.githubusercontent.com/LittleRichard/sormtger/master/bootstrap_install_sormtger.sh
./bootstrap_install_sormtger.sh
`

On your lappy and/or the RPi?  You may need to 'sudo apt-get install bash' but otherwise that should be one-button

**Comment by Panzer23** [comment]
Linux raspberrypi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux

**Comment by Panzer23** [comment]
@LittleRichard   I can dl just fine, but when I try to run the second command it either says access denied, or that the command is not found.

**Comment by LittleRichard** [comment]
Sounds like bash isn't installed, like I sort of expected.  should be an easy fix, we can take a look tonight.  what time will you be back?  i'm WFH because i feel sort of crappy, but i can definitely pop over anytime after 6-630 for an hour or two to discuss next moves

**Comment by Panzer23** [comment]
I installed bash I think. anyway I should be home around 5:30 or so, Ill text you.
