### ISSUE TITLE
Custom cam for pushing card in photo-tray

### ISSUE THREAD

**Issue by Panzer23** [LittleRichard/sormtger#12]

**Comment by Panzer23** [comment]
printed a part today, will see if it works when I get home.

**Comment by LittleRichard** [comment]
AHHHHHHHHH 'cam'!  That's what it's called!

**Comment by Panzer23** [comment]
I think....guessing based on my knowledge of cars

**Comment by Panzer23** [comment]
New solution used ,. No longer necessary
