### ISSUE TITLE
VM on lappy

### ISSUE THREAD

**Issue by Panzer23** [LittleRichard/sormtger#15]
@LittleRichard wtf was the name of the thingy I was supposed to install again?  I'm sorry, I forgot.

**Comment by LittleRichard** [comment]
* install on your laptop: http://www.vmware.com/products/workstation.html
* create a virtual machine in the 'player' that runs linux of some kind (i'd strongly recommend ubuntu)
* install 'liclipse' in your VM

and then we can do the rest of the setup together, we'll need to do virtual environments and stuff to get you going for development

**Comment by Panzer23** [comment]
@LittleRichard OK got the VM set up and running.  lemme know ill come over sometime and have you help me with the config

**Comment by Panzer23** [comment]
Works!!! Thanks Anson
