### ISSUE TITLE
Hardware Purchase List

### ISSUE THREAD

**Issue by Panzer23** [LittleRichard/sormtger#16]
US5881LUA - Hall effect sensor $2 - purchased
slip ring - not needed at this time
servo - cheap one $5 -purchased
adafruit pwm/servo hat - right angle pins, stacking gpio header, standoffs $23 - purchased
power supply for whole project (tired of having 3 wall worts) - not needed at this time
solenoids 6 - I  think - not needed at this time.

**Comment by Panzer23** [comment]
Updated:
Necessary:  
adafruit pwm/servo hat - right angle pins, stacking gpio header, standoffs $23
power supply for whole project (tired of having 3 wall worts) -$??
US5881LUA - Hall effect sensor $2
servo

Potential:
slip ring
solenoids
vex turntable gears

**Comment by LittleRichard** [comment]
i'll pick up this round of equipment, if you have it all in a cart pull the trigger and i'll wire it over.  otherwise, we can shop together on wednesday
