### ISSUE TITLE
Add DynamicCardDataDAO

### ISSUE THREAD

**Issue by LittleRichard** [LittleRichard/sormtger#35]
Add a DAO which will obscure the access to:
- a local cache to avoid excessive HTTP
- an external API to retrieve dynamic card data; chiefly price.

**Comment by LittleRichard** [comment]
For now the only dynamic data is price, but this will take the form of a script that can be run daily using the Scryfall wide-open API.  The script will update a new table in the database (dynamic_card_data) that has a foreign key to static_card_data.  It'll take a while to run because they ask you to go easy on their servers, but it won't be too bad.

Prices will be unique by name and set.  @Panzer23 , are there any sets with duplicate named cards that would have significantly different prices? I know sets have multiple copies of lands, but I don't care a ton there.

**Comment by Panzer23** [comment]
potentially ice age, and when we start looking into foils, then yes.  For now, unless it's a technical issue, I don't think we need to worry about it.

**Comment by LittleRichard** [comment]
Okay, it's probably for the best that I re-do the static card data
download-to-database operation to support duplicates better anyway.  Since
we don't have to deal with migrating existing data and I can just wipe the
database it's pretty easy to handle, and will be more robust in the future.

**Comment by LittleRichard** [comment]
Using Scryfall fixed a whole bunch of crappy code.  Instead of having to figure out how to map JSON data from one place to get the URLs of images from a different website, Scryfall provides the data AND URLs to the images.  The biggest boon is that source images will be more consistent, so the matching should improve.  The 2nd biggest boon is way better coverage of sets, since there's far less mangling things and handling edge cases.

Re-wrote the card data updater to use Scryfall exclusively, ran it overnight.  Aside from a few broken image links (which will hopefully self-heal over time), it worked great.  I still need to verify the data, clean up stale/dead code, and update the easy-insert DB 'binary' file.  I'll push a huge change to master sometime this week.

**Comment by LittleRichard** [comment]
Merged to master
