### ISSUE TITLE
add Adafruit_Servo_Driver to install

### ISSUE THREAD

**Issue by Panzer23** [LittleRichard/sormtger#41]
@LittleRichard  here is the code for the servo driver

git clone -b legacy https://github.com/adafruit/Adafruit-Raspberry-Pi-Python-Code.git
cd Adafruit-Raspberry-Pi-Python-Code
cd Adafruit_PWM_Servo_Driver

https://learn.adafruit.com/adafruit-16-channel-pwm-servo-hat-for-raspberry-pi/using-the-python-library

and a link to the product

**Comment by LittleRichard** [comment]
https://github.com/LittleRichard/sormtger/commit/5eaf4faef7259f5a00b8dab1028e99e6cc82ec3a#diff-137fc01abc671fbe3ef6d66386fed757

**Comment by LittleRichard** [comment]
@Panzer23, when you do a clean install this will come for free or you can bash the shell script in the commit linked above
