### ISSUE TITLE
Edge Cases

### ISSUE THREAD

**Issue by Panzer23** [LittleRichard/sormtger#5]
Likely common cases
- dual cards, like catch//release
- transform cards (name/set symbols on BOTH sides), like huntmaster of the fells
- flip-walkers - cycle of 5 planeswalkers that transform from creatures to walkers on the other side
- full art
- there are commander sets with their own symbols

Less likely, but still important to handle:
- Alpha: no symbol, black edge, only the artist on the bottom, rounder corners
- Beta: same as alpha, corners are now same as all the rest of the sets
- unlimited: dark printing, white boarders, no symbol, only artist on bottom
- revised: light printing, white boarders, no symbol, only artist on bottom
- Chronicles: white boarders, cards are from arabian nights, antiquities, legends, the dark and have those symbols
- meld cards like hanweir garrison with half a card on the other side.
- flip cards ( two names, set symbol on the bottom right) - should not be an issue right now, there are no reprints of these cards, like Kitsune Mystic

Rarer, low-priority:
- judge's promos and other have set symbols, some have the same symbol as the set the card came from
- Guru lands
- Pre-release promos
- Foils

**Comment by LittleRichard** [comment]
@Panzer23 , i just added a few and re-organized them by priority (as i understand it), can you take a look and edit/add as you see fit?

**Comment by Panzer23** [comment]
@LittleRichard re-edited to discuss the different types of flip cards.
flip cards - kitsune mystic
transform cards - huntmaster of the fells
morph cards - hanweir garrison
flip-walkers - Liliana, Heretical healer

**Comment by LittleRichard** [comment]
other than foils....

kinda covered all these when switching to scryfall and all-in on phash.. can always revisit as we find more, foils will be a project unto themselves
