### ISSUE TITLE
Explore scikit-image library

### ISSUE THREAD

**Issue by LittleRichard** [LittleRichard/sormtger#51]
The scikit-image library has a ton of functionality around advanced image processing, without going anywhere near something unwieldy like openCV.  For example, keypoint stuff:
http://scikit-image.org/docs/dev/auto_examples/features_detection/plot_orb.html#sphx-glr-auto-examples-features-detection-plot-orb-py

First, see how easy it is to install.  It's either already packaged with scipy and hence already available, or it's an extension of it and should be a quick addition.

Then, see if it's possible to do this against a generous crop of a symbol:
http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_label.html#sphx-glr-auto-examples-segmentation-plot-label-py

Great find @Panzer23

**Comment by LittleRichard** [comment]
While looking at `pyocr` in #53 , found an interesting library that promises to enhance text a bit:
https://github.com/jflesch/libpillowfight#stroke-width-transformation

**Comment by LittleRichard** [comment]
A good intro, and the histogram equalization seems like a good pre-filter
http://blog.yhat.com/posts/image-processing-with-scikit-image.html

**Comment by LittleRichard** [comment]
Tested out region thresholding, blob detection, and corner detection.  Added functions to the CardIdentifier that run each and display the results against the image.

Will stop for now, I don't want to get too far into this without better test images.  But it's definitely promising, if tricky to get right

**Comment by Panzer23** [comment]
Excellent,. Hopefully the pi works the motors and i can try out the new paper clip based OCAT Device in anger.



On Mon, Oct 31, 2016 at 7:31 PM -0600, "LittleRichard" <notifications@github.com<mailto:notifications@github.com>> wrote:


Tested out region thresholding, blob detection, and corner detection. Added functions to the CardIdentifier that run each and display the results against the image.

Will stop for now, I don't want to get too far into this without better test images. But it's definitely promising, if tricky to get right

-

**Comment by Panzer23** [comment]
Have you seen the app scryglass?  Might want to take a look.



On Mon, Oct 31, 2016 at 7:31 PM -0600, "LittleRichard" <notifications@github.com<mailto:notifications@github.com>> wrote:


Tested out region thresholding, blob detection, and corner detection. Added functions to the CardIdentifier that run each and display the results against the image.

Will stop for now, I don't want to get too far into this without better test images. But it's definitely promising, if tricky to get right

-

**Comment by LittleRichard** [comment]
Neat, I don't have time to watch the videos now but will later

**Comment by LittleRichard** [comment]
Try this for symbol detection:
http://scikit-image.org/docs/dev/auto_examples/edges/plot_contours.html#sphx-glr-auto-examples-edges-plot-contours-py
http://scikit-image.org/docs/dev/auto_examples/edges/plot_active_contours.html

**Comment by LittleRichard** [comment]
Contours are the answer!
![figure_1](https://cloud.githubusercontent.com/assets/8497969/20373085/b647cb00-ac3d-11e6-8344-e13cacba42c2.png)
![figure_1-1](https://cloud.githubusercontent.com/assets/8497969/20373086/b6490830-ac3d-11e6-848d-d417e72cd15c.png)
![figure_1-2](https://cloud.githubusercontent.com/assets/8497969/20373087/b64bca5c-ac3d-11e6-8d29-33e5bd226833.png)
![figure_1-3](https://cloud.githubusercontent.com/assets/8497969/20373088/b64dd7f2-ac3d-11e6-862e-36dc9e530ea1.png)

**Comment by Panzer23** [comment]
OMG


________________________________

**Comment by Panzer23** [comment]
I knew you would figure it out!

________________________________

**Comment by LittleRichard** [comment]
Closing, this road let to openCV and a whole bunch of changes but as of the latest master, simple cases work
