### ISSUE TITLE
Wiping Raspbian and reinstalling

### ISSUE THREAD

**Issue by Panzer23** [LittleRichard/sormtger#52]
End with: 
- A SD card image that has all this crap pre-installed so that, while we COULD do it from scratch, we never have to ever again.
  - Doubly important if my worst nightmare comes true and we have to compile tesseract from source

Need:
- Computer with SD/microSD reader
- microSD with at least 8GB space (we have 16)
- RPi
- Inputs for RPi :  Key/mouse  HDMI input (works with adapters)

Install instructions from RPi foundation:
(this has the instructions for direct burning of Raspbian to SD)
https://www.raspberrypi.org/learning/software-guide/
1. DL SD formatter : https://www.sdcard.org/downloads/formatter_4/index.html
2. DL NOOBS: https://downloads.raspberrypi.org/NOOBS_lite_latest
3. install formatter and open.
4. choose SD card to format and open options
   - choose FORMAT TYPE:  **FULL (erase)**
   - choose FORMAT SIZE ADJUSTMENT: **ON**
5. Format SD
6. Unzip NOOBS and copy all files to root of SD
7. SD into RPi and turn it on
8. Follow on screen instructions

These steps have worked for me, though I think it would be easier to use the direct burn to SD. The noobs lite DLs all necessary files, there is also NOOBS reg, which has all of the installation files offline (its 1.1gb file though)

**Comment by LittleRichard** [comment]
Problems fixed
* the raspbian package targets were out of date, causing miscellaneous failures
  * added `sudo apt-get update` to bootstrap
* the servo motor hat install requires virtualenv installed with other pip stuff (i guess it's pre-installed on ubuntu, so it worked for laptops)
  * moved the motor hat installation shell script calls to be after the pip install
* required jpeg library not included on raspbian, caused tesseract installation issues
  * added to the libraries installed

Problems I don't know how to fix yet
* The python tesseract wrapper requires tesseract version 3.04, but `apt-get tesseract-ocr` installs 3.03
  * The version installed using apt-get on ubuntu is 3.04, which is correct
    * This is because the ARM architecture binaries haven't been published to the debian package manager for 3.04 (yet).
* scipy (required for advanced p-hash algorithms and scikit-image) doesn't seem to install cleanly on the RPi (again, likely an ARM issue but not as sure)

**Comment by LittleRichard** [comment]
It is not possible to get the tesseract-ocr and the python library I've been using installed on the Rpi, because the python library requires a certain version of tesseract (3.04) for which binaries are not available because the RPi runs on an ARM processor.  We can

* install ubuntu 16.04 on the RPi
  * Will inevitably require the installation of a bunch of RPi stuff that comes with Raspbian
    * This will suck.
* use a python library that doesn't require the tesseract 3.04
  * found one, `pyocr`, that i will test now.
    * will require some re-writes, but should have all the same functionality

**Comment by Panzer23** [comment]
If you go onto the rpi webpage,. There are a lot of other distros that work with the rpi maybe one of them will work?



On Sun, Oct 30, 2016 at 6:41 PM -0600, "LittleRichard" <notifications@github.com<mailto:notifications@github.com>> wrote:


It is not possible to get the tesseract-ocr and the python library I've been using installed on the Rpi, because the python library requires a certain version of tesseract (3.04) for which binaries are not available because the RPi runs on an ARM processor. We can

  *   install ubuntu 16.04 on the RPi
     *   Will inevitably require the installation of a bunch of RPi stuff that comes with Raspbian
        *   This will suck.
  *   use a python library that doesn't require the tesseract 3.04
     *   found one, pyocr, that i will test now.
        *   will require some re-writes, but should have all the same functionality

-

**Comment by LittleRichard** [comment]
Good idea, I'm downloading ubuntu Mate at the same time as poking into this library.

**Comment by LittleRichard** [comment]
`pyocr` is a viable option, but I'd have to re-figure out how to do all the optimizations.  About to try @Panzer23 's idea before abandoning the current library.

**Comment by LittleRichard** [comment]
After an overnight compilation of numpy/scipy, Ubuntu MATE is our new OS!  Bootstrapped successfully, then went line-by-line through `install_sormtger.sh`, stopping before running `full_update_sormtger.sh`.  I haven't confirmed by running the sandbox against images, but everything installed correctly so I'm pretty confident.

Before running the migrators and testing, I'll make a copy of this 'clean install' image so that we never have to do all the apt-getting and pip installing again.

**Comment by Panzer23** [comment]
Crisis averted



On Mon, Oct 31, 2016 at 7:14 AM -0600, "LittleRichard" <notifications@github.com<mailto:notifications@github.com>> wrote:


After an overnight compilation of numpy/scipy, Ubuntu MATE is our new OS! Bootstrapped successfully, then went line-by-line through install_sormtger.sh, stopping before running full_update_sormtger.sh. I haven't confirmed by running the sandbox against images, but everything installed correctly so I'm pretty confident.

Before running the migrators and testing, I'll make a copy of this 'clean install' image so that we never have to do all the apt-getting and pip installing again.

-

**Comment by LittleRichard** [comment]
I have a backed-up image on my laptop, and a fully installed version on the RPi.  I'll drop it off at the house before Thursday, and we can transfer the backup from my laptop to yours whenever it's convenient.
