### ISSUE TITLE
enable i2c on unbuntu mate image

### ISSUE THREAD

**Issue by Panzer23** [LittleRichard/sormtger#54]
couple of things need to be added to /boot/config.txt

dtparam=i2c1=on
dtparam=i2c_arm=on

couple of things needed in modules:

    i2c-bcm2708 
    i2c-dev

with these added, was able to locate both boards

**Comment by LittleRichard** [comment]
We can close this, right?

**Comment by Panzer23** [comment]
no, I think we should get an image first so we don't have to do this again

**Comment by LittleRichard** [comment]
taking this ticket, will add to the install steps

**Comment by LittleRichard** [comment]
didn't do this with the latest image, once it's all settled in the final implementation on the latest OS i'll apply it to the installation scripts

**Comment by Panzer23** [comment]
Back to raspbian >>> issue no longer relevant
