### ISSUE TITLE
missing dependency for adafruit shit

### ISSUE THREAD

**Issue by Panzer23** [LittleRichard/sormtger#55]
our install needs:

python-smbus and maybe i2c-tools

**Comment by LittleRichard** [comment]
Those are apt-get things, right?  If so, feel free to add them install_libraries.sh as individual lines and commit them to the repo.

Once you've installed them to linux, we can re-make the backup image before getting weird doing anything else

**Comment by Panzer23** [comment]
@LittleRichard :  still having the same error pop up.  Maybe you can explain?

Traceback (most recent call last):
  File "/home/pi/Desktop/sormtger/server/firmware/cataloguer_hardware.py", line 5, in <module>
    import smbus
ImportError: No module named 'smbus'

**Comment by LittleRichard** [comment]
Its like a python package that was automatically installed for raspbian.
Can you find anything called smbus on pypi?

**Comment by Panzer23** [comment]
no, though to be fair, I did install a package called python-smbus, and have communicated to the boards through i2c-tools.  smbus is the protocol for i2c apparently.  it just seems like adafruit can't find that module when we are trying to use it in sormtger.

are we using python 2 or 3 for this build?  some of the ppls say it might be an issue in python version

**Comment by LittleRichard** [comment]
Python2.7

**Comment by LittleRichard** [comment]
try this one
`sudo apt-get install libi2c-dev`

**Comment by LittleRichard** [comment]
We can close this, right?

**Comment by Panzer23** [comment]
yup yup
