### ISSUE TITLE
review sets

### ISSUE THREAD

**Issue by LittleRichard** [LittleRichard/sormtger#66]
here's the exclude list, any adds from the full list below it?
SETS_THAT_DONT_EXIST = set((
        # 100% recycle of other sets
        MTGSets.CP1,
        MTGSets.CP2,
        MTGSets.CP3,
        MTGSets.RQS,
        MTGSets.MGB,
        MTGSets.ITP,
        # weird big cards
        MTGSets.VAN,
        # Online-only
        MTGSets.VMA,
        MTGSets.MED,
        MTGSets.ME2,
        MTGSets.ME3,
        MTGSets.ME4,
        MTGSets.TPR,
        MTGSets.TD0,
        MTGSets.PZ1,
        MTGSets.PZ2,
    ))

heres the enum list

TEN_ED = MTGSet("10e", "Tenth Edition")
    TWO_ED = MTGSet("2ed", "Unlimited Edition")
    THREE_ED = MTGSet("3ed", "Revised Edition")
    FOUR_ED = MTGSet("4ed", "Fourth Edition")
    FIVE_ED = MTGSet("5ed", "Fifth Edition")
    SIX_ED = MTGSet("6ed", "Classic Sixth Edition")
    SEVEN_ED = MTGSet("7ed", "Seventh Edition")
    EIGHT_ED = MTGSet("8ed", "Eighth Edition")
    NINE_ED = MTGSet("9ed", "Ninth Edition")
    AER = MTGSet("aer", "Aether Revolt")
    AKH = MTGSet("akh", "Amonkhet")
    ALA = MTGSet("ala", "Shards of Alara")
    ALL = MTGSet("all", "Alliances")
    APC = MTGSet("apc", "Apocalypse")
    ARB = MTGSet("arb", "Alara Reborn")
    ARC = MTGSet("arc", "Archenemy")
    ARN = MTGSet("arn", "Arabian Nights")
    ATH = MTGSet("ath", "Anthologies")
    ATQ = MTGSet("atq", "Antiquities")
    AVR = MTGSet("avr", "Avacyn Restored")
    BFZ = MTGSet("bfz", "Battle for Zendikar")
    BNG = MTGSet("bng", "Born of the Gods")
    BOK = MTGSet("bok", "Betrayers of Kamigawa")
    BRB = MTGSet("brb", "Battle Royale Box Set")
    BTD = MTGSet("btd", "Beatdown Box Set")
    C13 = MTGSet("c13", "Commander 2013")
    C14 = MTGSet("c14", "Commander 2014")
    C15 = MTGSet("c15", "Commander 2015")
    C16 = MTGSet("c16", "Commander 2016")
    CHK = MTGSet("chk", "Champions of Kamigawa")
    CHR = MTGSet("chr", "Chronicles")
    CM1 = MTGSet("cm1", "Commander's Arsenal")
    CMD = MTGSet("cmd", "Commander 2011")
    CN2 = MTGSet("cn2", "Conspiracy: Take the Crown")
    CNS = MTGSet("cns", "Conspiracy")
    CON = MTGSet("con", "Conflux")
    CP1 = MTGSet("cp1", "Magic 2015 Clash Pack")
    CP2 = MTGSet("cp2", "Fate Reforged Clash Pack")
    CP3 = MTGSet("cp3", "Magic Origins Clash Pack")
    CSP = MTGSet("csp", "Coldsnap")
    CST = MTGSet("cst", "Coldsnap Theme Decks")
    DD1 = MTGSet("dd1", "Duel Decks: Elves vs. Goblins")
    DD2 = MTGSet("dd2", "Duel Decks: Jace vs. Chandra")
    DDC = MTGSet("ddc", "Duel Decks: Divine vs. Demonic")
    DDD = MTGSet("ddd", "Duel Decks: Garruk vs. Liliana")
    DDE = MTGSet("dde", "Duel Decks: Phyrexia vs. the Coalition")
    DDF = MTGSet("ddf", "Duel Decks: Elspeth vs. Tezzeret")
    DDG = MTGSet("ddg", "Duel Decks: Knights vs. Dragons")
    DDH = MTGSet("ddh", "Duel Decks: Ajani vs. Nicol Bolas")
    DDI = MTGSet("ddi", "Duel Decks: Venser vs. Koth")
    DDJ = MTGSet("ddj", "Duel Decks: Izzet vs. Golgari")
    DDK = MTGSet("ddk", "Duel Decks: Sorin vs. Tibalt")
    DDL = MTGSet("ddl", "Duel Decks: Heroes vs. Monsters")
    DDM = MTGSet("ddm", "Duel Decks: Jace vs. Vraska")
    DDN = MTGSet("ddn", "Duel Decks: Speed vs. Cunning")
    DDO = MTGSet("ddo", "Duel Decks: Elspeth vs. Kiora")
    DDP = MTGSet("ddp", "Duel Decks: Zendikar vs. Eldrazi")
    DDQ = MTGSet("ddq", "Duel Decks: Blessed vs. Cursed")
    DDR = MTGSet("ddr", "Duel Decks: Nissa vs. Ob Nixilis")
    DDS = MTGSet("dds", "Duel Decks: Mind vs. Might")
    DGM = MTGSet("dgm", "Dragon's Maze")
    DIS = MTGSet("dis", "Dissension")
    DKA = MTGSet("dka", "Dark Ascension")
    DKM = MTGSet("dkm", "Deckmasters")
    DPA = MTGSet("dpa", "Duels of the Planeswalkers")
    DRB = MTGSet("drb", "From the Vault: Dragons")
    DRK = MTGSet("drk", "The Dark")
    DST = MTGSet("dst", "Darksteel")
    DTK = MTGSet("dtk", "Dragons of Tarkir")
    DVD = MTGSet("dvd", "Duel Decks Anthology: Divine vs. Demonic")
    EMA = MTGSet("ema", "Eternal Masters")
    EMN = MTGSet("emn", "Eldritch Moon")
    EVE = MTGSet("eve", "Eventide")
    EVG = MTGSet("evg", "Duel Decks Anthology: Elves vs. Goblins")
    EXO = MTGSet("exo", "Exodus")
    EXP = MTGSet("exp", "Zendikar Expeditions")
    F01 = MTGSet("f01", "Friday Night Magic 2001")
    F02 = MTGSet("f02", "Friday Night Magic 2002")
    F03 = MTGSet("f03", "Friday Night Magic 2003")
    F04 = MTGSet("f04", "Friday Night Magic 2004")
    F05 = MTGSet("f05", "Friday Night Magic 2005")
    F06 = MTGSet("f06", "Friday Night Magic 2006")
    F07 = MTGSet("f07", "Friday Night Magic 2007")
    F08 = MTGSet("f08", "Friday Night Magic 2008")
    F09 = MTGSet("f09", "Friday Night Magic 2009")
    F10 = MTGSet("f10", "Friday Night Magic 2010")
    F11 = MTGSet("f11", "Friday Night Magic 2011")
    F12 = MTGSet("f12", "Friday Night Magic 2012")
    F13 = MTGSet("f13", "Friday Night Magic 2013")
    F14 = MTGSet("f14", "Friday Night Magic 2014")
    F15 = MTGSet("f15", "Friday Night Magic 2015")
    F16 = MTGSet("f16", "Friday Night Magic 2016")
    F17 = MTGSet("f17", "Friday Night Magic 2017")
    FDN = MTGSet("5dn", "Fifth Dawn")
    FEM = MTGSet("fem", "Fallen Empires")
    FNM = MTGSet("fnm", "Friday Night Magic 2000")
    FRF = MTGSet("frf", "Fate Reforged")
    FUT = MTGSet("fut", "Future Sight")
    G00 = MTGSet("g00", "Judge Gift Cards 2000")
    G01 = MTGSet("g01", "Judge Gift Cards 2001")
    G02 = MTGSet("g02", "Judge Gift Cards 2002")
    G03 = MTGSet("g03", "Judge Gift Cards 2003")
    G04 = MTGSet("g04", "Judge Gift Cards 2004")
    G05 = MTGSet("g05", "Judge Gift Cards 2005")
    G06 = MTGSet("g06", "Judge Gift Cards 2006")
    G07 = MTGSet("g07", "Judge Gift Cards 2007")
    G08 = MTGSet("g08", "Judge Gift Cards 2008")
    G09 = MTGSet("g09", "Judge Gift Cards 2009")
    G10 = MTGSet("g10", "Judge Gift Cards 2010")
    G11 = MTGSet("g11", "Judge Gift Cards 2011")
    G99 = MTGSet("g99", "Judge Gift Cards 1999")
    GPT = MTGSet("gpt", "Guildpact")
    GTC = MTGSet("gtc", "Gatecrash")
    GVL = MTGSet("gvl", "Duel Decks Anthology: Garruk vs. Liliana")
    H09 = MTGSet("h09", "Premium Deck Series: Slivers")
    HHO = MTGSet("hho", "Happy Holidays")
    HML = MTGSet("hml", "Homelands")
    HOP = MTGSet("hop", "Planechase")
    ICE = MTGSet("ice", "Ice Age")
    INV = MTGSet("inv", "Invasion")
    ISD = MTGSet("isd", "Innistrad")
    ITP = MTGSet("itp", "Introductory Two-Player Set")
    J12 = MTGSet("j12", "Judge Gift Cards 2012")
    J13 = MTGSet("j13", "Judge Gift Cards 2013")
    J14 = MTGSet("j14", "Judge Gift Cards 2014")
    J15 = MTGSet("j15", "Judge Gift Cards 2015")
    J16 = MTGSet("j16", "Judge Gift Cards 2016")
    J17 = MTGSet("j17", "Judge Gift Cards 2017")
    JGP = MTGSet("jgp", "Judge Gift Cards 1998")
    JOU = MTGSet("jou", "Journey into Nyx")
    JUD = MTGSet("jud", "Judgment")
    JVC = MTGSet("jvc", "Duel Decks Anthology: Jace vs. Chandra")
    KLD = MTGSet("kld", "Kaladesh")
    KTK = MTGSet("ktk", "Khans of Tarkir")
    LEA = MTGSet("lea", "Limited Edition Alpha")
    LEB = MTGSet("leb", "Limited Edition Beta")
    LEG = MTGSet("leg", "Legends")
    LGN = MTGSet("lgn", "Legions")
    LRW = MTGSet("lrw", "Lorwyn")
    M10 = MTGSet("m10", "Magic 2010")
    M11 = MTGSet("m11", "Magic 2011")
    M12 = MTGSet("m12", "Magic 2012")
    M13 = MTGSet("m13", "Magic 2013")
    M14 = MTGSet("m14", "Magic 2014")
    M15 = MTGSet("m15", "Magic 2015")
    MBS = MTGSet("mbs", "Mirrodin Besieged")
    MD1 = MTGSet("md1", "Modern Event Deck 2014")
    ME2 = MTGSet("me2", "Masters Edition II")
    ME3 = MTGSet("me3", "Masters Edition III")
    ME4 = MTGSet("me4", "Masters Edition IV")
    MED = MTGSet("med", "Masters Edition")
    MGB = MTGSet("mgb", "Multiverse Gift Box")
    MIR = MTGSet("mir", "Mirage")
    MM2 = MTGSet("mm2", "Modern Masters 2015")
    MM3 = MTGSet("mm3", "Modern Masters 2017")
    MMA = MTGSet("mma", "Modern Masters")
    MMQ = MTGSet("mmq", "Mercadian Masques")
    MOR = MTGSet("mor", "Morningtide")
    MP2 = MTGSet("mp2", "Amonkhet Invocations")
    MPR = MTGSet("mpr", "Magic Player Rewards 2001-2002")
    MPS = MTGSet("mps", "Kaladesh Inventions")
    MRD = MTGSet("mrd", "Mirrodin")
    NEM = MTGSet("nem", "Nemesis")
    NPH = MTGSet("nph", "New Phyrexia")
    ODY = MTGSet("ody", "Odyssey")
    OGW = MTGSet("ogw", "Oath of the Gatewatch")
    ONS = MTGSet("ons", "Onslaught")
    ORI = MTGSet("ori", "Magic Origins")
    P02 = MTGSet("p02", "Portal: Second Age")
    P03 = MTGSet("p03", "Magic Player Rewards 2003")
    P04 = MTGSet("p04", "Magic Player Rewards 2004")
    P05 = MTGSet("p05", "Magic Player Rewards 2005")
    P06 = MTGSet("p06", "Magic Player Rewards 2006")
    P07 = MTGSet("p07", "Magic Player Rewards 2007")
    P08 = MTGSet("p08", "Magic Player Rewards 2008")
    P09 = MTGSet("p09", "Magic Player Rewards 2009")
    P10 = MTGSet("p10", "Magic Player Rewards 2010")
    P11 = MTGSet("p11", "Magic Player Rewards 2011")
    P15A = MTGSet("p15a", "15th Anniversary Cards")
    P2HG = MTGSet("p2hg", "Two-Headed Giant Tournament")
    PAER = MTGSet("paer", "Aether Revolt Promos")
    PAKH = MTGSet("pakh", "Amonkhet Promos")
    PALP = MTGSet("palp", "Asia Pacific Land Program")
    PARL = MTGSet("parl", "Arena League")
    PC2 = MTGSet("pc2", "Planechase 2012")
    PCA = MTGSet("pca", "Planechase Anthology")
    PCEL = MTGSet("pcel", "Celebration Cards")
    PCMP = MTGSet("pcmp", "Champs and States")
    PCY = MTGSet("pcy", "Prophecy")
    PD2 = MTGSet("pd2", "Premium Deck Series: Fire and Lightning")
    PD3 = MTGSet("pd3", "Premium Deck Series: Graveborn")
    PDD2 = MTGSet("pdd2", "Duel Decks: Jace vs. Chandra Japanese Promos")
    PDRC = MTGSet("pdrc", "Dragon Con")
    PELP = MTGSet("pelp", "European Land Program")
    PEMN = MTGSet("pemn", "Eldritch Moon Promos")
    PGMX = MTGSet("pgmx", "Gleemax Project")
    PGPX = MTGSet("pgpx", "Grand Prix Promos")
    PGRU = MTGSet("pgru", "Guru")
    PGTW = MTGSet("pgtw", "Gateway")
    PKLD = MTGSet("pkld", "Kaladesh Promos")
    PLC = MTGSet("plc", "Planar Chaos")
    PLGM = MTGSet("plgm", "DCI Legend Membership")
    PLPA = MTGSet("plpa", "Launch Parties")
    PLS = MTGSet("pls", "Planeshift")
    PMEI = MTGSet("pmei", "Media Inserts")
    PMGD = MTGSet("pmgd", "Magic Game Day")
    POGW = MTGSet("pogw", "Oath of the Gatewatch Promos")
    POR = MTGSet("por", "Portal")
    PPOD = MTGSet("ppod", "Portal Demo Game")
    PPRE = MTGSet("ppre", "Prerelease Events")
    PPRO = MTGSet("ppro", "Pro Tour Promos")
    PREL = MTGSet("prel", "Release Events")
    PS14 = MTGSet("ps14", "San Diego Comic-Con 2014")
    PS15 = MTGSet("ps15", "San Diego Comic-Con 2015")
    PS16 = MTGSet("ps16", "San Diego Comic-Con 2016")
    PSDC = MTGSet("psdc", "San Diego Comic-Con 2013")
    PSOI = MTGSet("psoi", "Shadows over Innistrad Promos")
    PSUM = MTGSet("psum", "Summer of Magic")
    PSUS = MTGSet("psus", "Super Series")
    PTK = MTGSet("ptk", "Portal: Three Kingdoms")
    PVAN = MTGSet("pvan", "Vanguard Series")
    PWCQ = MTGSet("pwcq", "World Magic Cup Qualifiers")
    PWOR = MTGSet("pwor", "Worlds")
    PWOS = MTGSet("pwos", "Wizards of the Coast Online Store")
    PWPN = MTGSet("pwpn", "Wizards Play Network")
    PZ1 = MTGSet("pz1", "Legendary Cube")
    PZ2 = MTGSet("pz2", "You Make the Cube")
    RAV = MTGSet("rav", "Ravnica: City of Guilds")
    ROE = MTGSet("roe", "Rise of the Eldrazi")
    RQS = MTGSet("rqs", "Rivals Quick Start Set")
    RTR = MTGSet("rtr", "Return to Ravnica")
    S00 = MTGSet("s00", "Starter 2000")
    S99 = MTGSet("s99", "Starter 1999")
    SCG = MTGSet("scg", "Scourge")
    SHM = MTGSet("shm", "Shadowmoor")
    SOI = MTGSet("soi", "Shadows over Innistrad")
    SOK = MTGSet("sok", "Saviors of Kamigawa")
    SOM = MTGSet("som", "Scars of Mirrodin")
    STH = MTGSet("sth", "Stronghold")
    TD0 = MTGSet("td0", "Magic Online Theme Decks")
    TD2 = MTGSet("td2", "Duel Decks: Mirrodin Pure vs. New Phyrexia")
    THS = MTGSet("ths", "Theros")
    TMP = MTGSet("tmp", "Tempest")
    TOR = MTGSet("tor", "Torment")
    TPR = MTGSet("tpr", "Tempest Remastered")
    TSB = MTGSet("tsb", "Time Spiral Timeshifted")
    TSP = MTGSet("tsp", "Time Spiral")
    UDS = MTGSet("uds", "Urza's Destiny")
    UGIN = MTGSet("ugin", "Ugin's Fate")
    UGL = MTGSet("ugl", "Unglued")
    ULG = MTGSet("ulg", "Urza's Legacy")
    UNH = MTGSet("unh", "Unhinged")
    USG = MTGSet("usg", "Urza's Saga")
    V09 = MTGSet("v09", "From the Vault: Exiled")
    V10 = MTGSet("v10", "From the Vault: Relics")
    V11 = MTGSet("v11", "From the Vault: Legends")
    V12 = MTGSet("v12", "From the Vault: Realms")
    V13 = MTGSet("v13", "From the Vault: Twenty")
    V14 = MTGSet("v14", "From the Vault: Annihilation")
    V15 = MTGSet("v15", "From the Vault: Angels")
    V16 = MTGSet("v16", "From the Vault: Lore")
    VAN = MTGSet("van", "Magic Online Avatars")
    VIS = MTGSet("vis", "Visions")
    VMA = MTGSet("vma", "Vintage Masters")
    W16 = MTGSet("w16", "Welcome Deck 2016")
    WTH = MTGSet("wth", "Weatherlight")
    WWK = MTGSet("wwk", "Worldwake")
    ZEN = MTGSet("zen", "Zendikar")

**Comment by Panzer23** [comment]
I think you caught everything!
