### ISSUE TITLE
Adafruit Stepper Motor Driver

### ISSUE THREAD

**Issue by Panzer23** [LittleRichard/sormtger#77]
As discussed previously,  the stepper motor driver from adafruit is ok, but is dropping steps and isnt consitently giving the torque necessary to drive a fully loaded table.  because of this we need to rethink our options when it comes to how to drive the table.  I have a few ideas to think through:

1. I want to first try a bigger stepper motor, which will require MORE POWAH!!!
2. Trying the new stepper motor driver, which we can control with a GPIO pin only.  
3. if necessary, we also have the option of using pigpio python library which controls the GPIO pin w/ hardware instead of software.
4. we also have an arduino controlling the light at this point so we might be able to take advantage of that to drive the motor as well.

**Comment by Panzer23** [comment]
http://tropical-labs.com/shop/  maybe this?

**Comment by Panzer23** [comment]
OR....we could put a magnet under each hopper and count the number that we pass on the way to the next one

**Comment by LittleRichard** [comment]
I trust your judgement on the stepper motor, but I'd lean toward ease-of-use over power and price.  The less GPIO and gluing together of software<->hardware, the better IMO.  That said, it's not hard to rig something like that up so if the perfect motor requires some manual pin control, oh well.  Just bear in mind that manual pin stuff that uses the main CPU means that each card sorted will take more time (probably not significantly though)

**Comment by Panzer23** [comment]
yea I appreciate that, luckily it only uses 2 GPIO pins, and one is only set once per rotation (direction pin).  If it is bogging us down significantly, we can take advantage of the MCU that is running the light rn to do that for us as well, just connecting serially to it to transmit number of steps etc.

**Comment by Panzer23** [comment]
that motor hat was just WAAAAYYYY to troublesome to continue using.

**Comment by LittleRichard** [comment]
Makes sense about the pins, I'm sure its negligible time, and re:
magnets... I love the idea of putting a magnet at each spot, but how would
you identify zero? At first it wouldn't matter which is zero, but if you
paused a batch you'd need to align to the correct zero on resuming
